#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  Flow:
    session:
      inactivityTimeout: 9999999
    security:
        filters: []

    http:
      baseUri: http://satisfy.flow/

Famelo:
  Satisfy:
    Email:
      "no-reply@cobus-kundenzufriedenheit.de": COBUS ConCept GmbH

  Kundenbefragung:
    E-Mails:
      MoreInformation:
        - mneuhaus@famelo.com

  Impersonate:
    Role: Famelo.Satisfy:Administrator