#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  TypoScript:
    debugMode: false
    catchRuntimeExceptions: false
  Flow:
    persistence:
      backendOptions:
        host: 127.0.0.1
        dbname: flow-adu
        user: main
        password: main
    core:
      phpBinaryPathAndFilename: /usr/bin/php
    session:
      inactivityTimeout: 9999999
    security:
        filters: []
