#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  TypoScript:
    debugMode: FALSE
    catchRuntimeExceptions: FALSE
  Flow:
    persistence:
      backendOptions:
        host: 127.0.0.1
        dbname: flow-adu
        user: main
        password: main

Sandstorm:
  Plumber:
    # should we enable profiling, or just use Plumber as frontend for visualizing
    # profiling runs collected by other profiling collectors (such as the TYPO3 extension)
    enableProfiling: true
    calculations:
      navigationViewHelper:
        label: 'NavigationViewHelper'
        type: regex
        regex: '#Famelo\\Navigation\\ViewHelpers\\NavigationViewHelper::render#'
        metric: time
        subtype: sum