#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  TypoScript:
    handleRenderingExceptions: throw
    debugMode: false
    catchRuntimeExceptions: false
  Flow:
    persistence:
      doctrine:
        sqlLogger: 'TYPO3\Flow\Persistence\Doctrine\Logging\SqlLogger'
      backendOptions:
        driver: 'pdo_mysql'
        dbname: 'flow-satisfy'
        user: 'main'
        password: 'main'
        host: 'localhost'

Famelo:
  Messaging:
    redirectAllMessagesTo: mneuhaus@famelo.de